// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6Ba5W8Z0B9NkxKT5TVQLg7tFYQU4FU6Y',
    appId: '1:71170496441:web:43037d0060b338d1960868',
    messagingSenderId: '71170496441',
    projectId: 'social-app-df3c6',
    authDomain: 'social-app-df3c6.firebaseapp.com',
    storageBucket: 'social-app-df3c6.appspot.com',
    measurementId: 'G-02B05ZGTX6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATkYA0z-mJwUMbm4YWdgi00kem10WX36s',
    appId: '1:71170496441:android:3cd5d04f715ae3a7960868',
    messagingSenderId: '71170496441',
    projectId: 'social-app-df3c6',
    storageBucket: 'social-app-df3c6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHUokfnu3K6rCYuNUqIivjHz-sDnEsuVU',
    appId: '1:71170496441:ios:597eb6d6b1b95805960868',
    messagingSenderId: '71170496441',
    projectId: 'social-app-df3c6',
    storageBucket: 'social-app-df3c6.appspot.com',
    iosBundleId: 'com.example.socialApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAHUokfnu3K6rCYuNUqIivjHz-sDnEsuVU',
    appId: '1:71170496441:ios:d8aad683719464c3960868',
    messagingSenderId: '71170496441',
    projectId: 'social-app-df3c6',
    storageBucket: 'social-app-df3c6.appspot.com',
    iosBundleId: 'com.example.socialApp.RunnerTests',
  );
}
